FROM python:3.9-slim-buster
WORKDIR /app
COPY app/. /app/
RUN pip install --no-cache-dir -r requirements.txt
ENTRYPOINT ["python", "app.py"]

#docker run --env-file=.env mehtahcriticchatgptinslack:latest